# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'activity_mapper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(400, 440)
        Form.setMinimumSize(QtCore.QSize(400, 440))
        Form.setMaximumSize(QtCore.QSize(400, 440))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icon/action.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frm_header_frame = QtWidgets.QFrame(Form)
        self.frm_header_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frm_header_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_header_frame.setObjectName("frm_header_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frm_header_frame)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lbl_projectId = QtWidgets.QLabel(self.frm_header_frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_projectId.setFont(font)
        self.lbl_projectId.setStyleSheet("color: #F50A77")
        self.lbl_projectId.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_projectId.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_projectId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_projectId.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_projectId.setObjectName("lbl_projectId")
        self.verticalLayout_3.addWidget(self.lbl_projectId)
        self.lbl_task_name = QtWidgets.QLabel(self.frm_header_frame)
        self.lbl_task_name.setMinimumSize(QtCore.QSize(0, 50))
        self.lbl_task_name.setMaximumSize(QtCore.QSize(16777215, 16777213))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_task_name.setFont(font)
        self.lbl_task_name.setStyleSheet("color: #145479;\n"
"font-weight: bold")
        self.lbl_task_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_task_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_task_name.setScaledContents(True)
        self.lbl_task_name.setWordWrap(True)
        self.lbl_task_name.setIndent(1)
        self.lbl_task_name.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_task_name.setObjectName("lbl_task_name")
        self.verticalLayout_3.addWidget(self.lbl_task_name)
        self.verticalLayout_5.addWidget(self.frm_header_frame)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_activity = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_activity.setFont(font)
        self.lbl_activity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_activity.setIndent(5)
        self.lbl_activity.setObjectName("lbl_activity")
        self.horizontalLayout_3.addWidget(self.lbl_activity)
        self.dta_activity_date = QtWidgets.QDateEdit(self.frame)
        self.dta_activity_date.setMinimumSize(QtCore.QSize(100, 0))
        self.dta_activity_date.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dta_activity_date.setCalendarPopup(True)
        self.dta_activity_date.setDate(QtCore.QDate(1900, 1, 1))
        self.dta_activity_date.setObjectName("dta_activity_date")
        self.horizontalLayout_3.addWidget(self.dta_activity_date)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setIndent(-1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txt_activity_description = QtWidgets.QPlainTextEdit(self.frame)
        self.txt_activity_description.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txt_activity_description.setTabChangesFocus(True)
        self.txt_activity_description.setObjectName("txt_activity_description")
        self.verticalLayout.addWidget(self.txt_activity_description)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.cbx_keep_attention = QtWidgets.QCheckBox(self.frame)
        self.cbx_keep_attention.setObjectName("cbx_keep_attention")
        self.verticalLayout_4.addWidget(self.cbx_keep_attention)
        self.verticalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setStyleSheet("border: 1px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_ok = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.btn_ok.setFont(font)
        self.btn_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ok.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ok.setAutoFillBackground(False)
        self.btn_ok.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_ok.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/icon/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ok.setIcon(icon1)
        self.btn_ok.setIconSize(QtCore.QSize(32, 32))
        self.btn_ok.setAutoDefault(True)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.btn_activity_inspector = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_activity_inspector.sizePolicy().hasHeightForWidth())
        self.btn_activity_inspector.setSizePolicy(sizePolicy)
        self.btn_activity_inspector.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_activity_inspector.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_activity_inspector.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_activity_inspector.setText("")
        self.btn_activity_inspector.setIcon(icon)
        self.btn_activity_inspector.setIconSize(QtCore.QSize(32, 32))
        self.btn_activity_inspector.setObjectName("btn_activity_inspector")
        self.horizontalLayout.addWidget(self.btn_activity_inspector)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.dta_activity_date, self.txt_activity_description)
        Form.setTabOrder(self.txt_activity_description, self.cbx_keep_attention)
        Form.setTabOrder(self.cbx_keep_attention, self.btn_activity_inspector)
        Form.setTabOrder(self.btn_activity_inspector, self.btn_ok)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Czynność"))
        self.lbl_projectId.setText(_translate("Form", "Numer Inwestycji"))
        self.lbl_task_name.setText(_translate("Form", "Nazwa zadania"))
        self.lbl_activity.setText(_translate("Form", "Data"))
        self.dta_activity_date.setDisplayFormat(_translate("Form", "yyyy.MM.dd"))
        self.label.setText(_translate("Form", "Czynność"))
        self.cbx_keep_attention.setText(_translate("Form", "Obserwuj"))
        self.btn_ok.setToolTip(_translate("Form", "Zapisz"))
        self.btn_activity_inspector.setToolTip(_translate("Form", "Katalog czynności"))
import res.main_form_rc
