# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'action_inspector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(500, 440)
        Form.setMinimumSize(QtCore.QSize(500, 440))
        Form.setMaximumSize(QtCore.QSize(600, 440))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icon/action.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lstvw_actions = QtWidgets.QListView(Form)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lstvw_actions.setFont(font)
        self.lstvw_actions.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lstvw_actions.setFrameShape(QtWidgets.QFrame.Box)
        self.lstvw_actions.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lstvw_actions.setAlternatingRowColors(True)
        self.lstvw_actions.setWordWrap(True)
        self.lstvw_actions.setItemAlignment(QtCore.Qt.AlignLeading)
        self.lstvw_actions.setObjectName("lstvw_actions")
        self.horizontalLayout.addWidget(self.lstvw_actions)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Czynności"))
import res.main_form_rc
