# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dictionary_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(600, 600)
        Form.setMinimumSize(QtCore.QSize(600, 600))
        Form.setMaximumSize(QtCore.QSize(600, 600))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icon/logo_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_5.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(8)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_dictionary_name = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_dictionary_name.setFont(font)
        self.lbl_dictionary_name.setStyleSheet("color: #145479;\n"
"font-weight: bold")
        self.lbl_dictionary_name.setObjectName("lbl_dictionary_name")
        self.horizontalLayout_2.addWidget(self.lbl_dictionary_name)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.txt_search = QtWidgets.QLineEdit(self.frame_2)
        self.txt_search.setMinimumSize(QtCore.QSize(232, 25))
        self.txt_search.setStyleSheet("border: 1px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"")
        self.txt_search.setClearButtonEnabled(True)
        self.txt_search.setObjectName("txt_search")
        self.horizontalLayout_2.addWidget(self.txt_search)
        self.btn_search = QtWidgets.QPushButton(self.frame_2)
        self.btn_search.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_search.setStyleSheet("")
        self.btn_search.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/icon/filter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon1)
        self.btn_search.setIconSize(QtCore.QSize(25, 25))
        self.btn_search.setCheckable(True)
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_2.addWidget(self.btn_search)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.tblwgt_dictionary = QtWidgets.QTableWidget(self.frame_2)
        self.tblwgt_dictionary.setMinimumSize(QtCore.QSize(0, 333))
        self.tblwgt_dictionary.setFrameShape(QtWidgets.QFrame.Box)
        self.tblwgt_dictionary.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tblwgt_dictionary.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblwgt_dictionary.setAlternatingRowColors(True)
        self.tblwgt_dictionary.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblwgt_dictionary.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tblwgt_dictionary.setGridStyle(QtCore.Qt.DashLine)
        self.tblwgt_dictionary.setColumnCount(2)
        self.tblwgt_dictionary.setObjectName("tblwgt_dictionary")
        self.tblwgt_dictionary.setRowCount(0)
        self.tblwgt_dictionary.horizontalHeader().setCascadingSectionResizes(True)
        self.tblwgt_dictionary.horizontalHeader().setDefaultSectionSize(50)
        self.tblwgt_dictionary.horizontalHeader().setMinimumSectionSize(25)
        self.tblwgt_dictionary.horizontalHeader().setStretchLastSection(True)
        self.tblwgt_dictionary.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tblwgt_dictionary)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_element_value = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_element_value.setFont(font)
        self.lbl_element_value.setStyleSheet("color: #145479;\n"
"font-weight: bold")
        self.lbl_element_value.setObjectName("lbl_element_value")
        self.verticalLayout_4.addWidget(self.lbl_element_value)
        self.txt_element = QtWidgets.QPlainTextEdit(self.frame_3)
        self.txt_element.setMinimumSize(QtCore.QSize(0, 0))
        self.txt_element.setMaximumSize(QtCore.QSize(16777215, 95))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.txt_element.setFont(font)
        self.txt_element.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.txt_element.setTabChangesFocus(True)
        self.txt_element.setReadOnly(True)
        self.txt_element.setObjectName("txt_element")
        self.verticalLayout_4.addWidget(self.txt_element)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setStyleSheet("border: 1px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_add = QtWidgets.QPushButton(self.frame)
        self.btn_add.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_add.setMaximumSize(QtCore.QSize(50, 40))
        self.btn_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_add.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_add.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/icon/plus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_add.setIcon(icon2)
        self.btn_add.setIconSize(QtCore.QSize(32, 32))
        self.btn_add.setObjectName("btn_add")
        self.horizontalLayout.addWidget(self.btn_add)
        self.btn_edit = QtWidgets.QPushButton(self.frame)
        self.btn_edit.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_edit.setMaximumSize(QtCore.QSize(50, 40))
        self.btn_edit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_edit.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_edit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/icon/pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit.setIcon(icon3)
        self.btn_edit.setIconSize(QtCore.QSize(32, 32))
        self.btn_edit.setObjectName("btn_edit")
        self.horizontalLayout.addWidget(self.btn_edit)
        self.btn_remove = QtWidgets.QPushButton(self.frame)
        self.btn_remove.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_remove.setMaximumSize(QtCore.QSize(50, 40))
        self.btn_remove.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_remove.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_remove.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/icon/decline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_remove.setIcon(icon4)
        self.btn_remove.setIconSize(QtCore.QSize(32, 32))
        self.btn_remove.setObjectName("btn_remove")
        self.horizontalLayout.addWidget(self.btn_remove)
        spacerItem1 = QtWidgets.QSpacerItem(345, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_ok = QtWidgets.QPushButton(self.frame)
        self.btn_ok.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_ok.setMaximumSize(QtCore.QSize(50, 40))
        self.btn_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ok.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_ok.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/res/icon/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ok.setIcon(icon5)
        self.btn_ok.setIconSize(QtCore.QSize(32, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.verticalLayout_5.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.tblwgt_dictionary, self.txt_element)
        Form.setTabOrder(self.txt_element, self.txt_search)
        Form.setTabOrder(self.txt_search, self.btn_search)
        Form.setTabOrder(self.btn_search, self.btn_add)
        Form.setTabOrder(self.btn_add, self.btn_edit)
        Form.setTabOrder(self.btn_edit, self.btn_remove)
        Form.setTabOrder(self.btn_remove, self.btn_ok)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Słownik"))
        self.lbl_dictionary_name.setText(_translate("Form", "Słownik"))
        self.btn_search.setToolTip(_translate("Form", "Filtruj"))
        self.lbl_element_value.setText(_translate("Form", "Element"))
        self.btn_add.setToolTip(_translate("Form", "Dodaj element"))
        self.btn_edit.setToolTip(_translate("Form", "Edytuj element"))
        self.btn_remove.setToolTip(_translate("Form", "Usuń element"))
        self.btn_ok.setToolTip(_translate("Form", "Zapisz"))
import res.main_form_rc
