# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'document_mapper.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(444, 428)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(444, 428))
        Form.setMaximumSize(QtCore.QSize(444, 428))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.StrongFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icon/documents.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frm_header_frame = QtWidgets.QFrame(Form)
        self.frm_header_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frm_header_frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frm_header_frame.setObjectName("frm_header_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frm_header_frame)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_projectId = QtWidgets.QLabel(self.frm_header_frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_projectId.setFont(font)
        self.lbl_projectId.setStyleSheet("color: #F50A77")
        self.lbl_projectId.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_projectId.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.lbl_projectId.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_projectId.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_projectId.setObjectName("lbl_projectId")
        self.verticalLayout.addWidget(self.lbl_projectId)
        self.lbl_task_name = QtWidgets.QLabel(self.frm_header_frame)
        self.lbl_task_name.setMinimumSize(QtCore.QSize(0, 40))
        self.lbl_task_name.setMaximumSize(QtCore.QSize(16777215, 16777213))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_task_name.setFont(font)
        self.lbl_task_name.setStyleSheet("color: #145479;\n"
"font-weight: bold")
        self.lbl_task_name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_task_name.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_task_name.setWordWrap(True)
        self.lbl_task_name.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.lbl_task_name.setObjectName("lbl_task_name")
        self.verticalLayout.addWidget(self.lbl_task_name)
        self.verticalLayout_3.addWidget(self.frm_header_frame)
        self.frame = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(6, 6, 6, 6)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, -1, 2)
        self.formLayout.setSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.lbl_inflow = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_inflow.setFont(font)
        self.lbl_inflow.setObjectName("lbl_inflow")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_inflow)
        self.dta_inflow = QtWidgets.QDateEdit(self.frame)
        self.dta_inflow.setMinimumSize(QtCore.QSize(100, 0))
        self.dta_inflow.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dta_inflow.setCalendarPopup(True)
        self.dta_inflow.setDate(QtCore.QDate(1900, 1, 1))
        self.dta_inflow.setObjectName("dta_inflow")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dta_inflow)
        self.lbl_document_name = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_document_name.setFont(font)
        self.lbl_document_name.setObjectName("lbl_document_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_document_name)
        self.cbo_document_name = QtWidgets.QComboBox(self.frame)
        self.cbo_document_name.setEditable(False)
        self.cbo_document_name.setMaxVisibleItems(20)
        self.cbo_document_name.setObjectName("cbo_document_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.cbo_document_name)
        self.lbl_document_sign = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_document_sign.setFont(font)
        self.lbl_document_sign.setObjectName("lbl_document_sign")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_document_sign)
        self.txt_document_sign = QtWidgets.QLineEdit(self.frame)
        self.txt_document_sign.setObjectName("txt_document_sign")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_document_sign)
        self.lbl_document_issue = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_document_issue.setFont(font)
        self.lbl_document_issue.setObjectName("lbl_document_issue")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_document_issue)
        self.dta_document_issue = QtWidgets.QDateEdit(self.frame)
        self.dta_document_issue.setMinimumSize(QtCore.QSize(100, 0))
        self.dta_document_issue.setMaximumSize(QtCore.QSize(100, 16777215))
        self.dta_document_issue.setCalendarPopup(True)
        self.dta_document_issue.setDate(QtCore.QDate(1900, 1, 1))
        self.dta_document_issue.setObjectName("dta_document_issue")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dta_document_issue)
        self.lbl_info = QtWidgets.QLabel(self.frame)
        self.lbl_info.setObjectName("lbl_info")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_info)
        self.lbl_file = QtWidgets.QLabel(self.frame)
        self.lbl_file.setObjectName("lbl_file")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_file)
        self.txt_file = QtWidgets.QLineEdit(self.frame)
        self.txt_file.setEnabled(True)
        self.txt_file.setReadOnly(True)
        self.txt_file.setObjectName("txt_file")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_file)
        self.txt_info = QtWidgets.QPlainTextEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_info.sizePolicy().hasHeightForWidth())
        self.txt_info.setSizePolicy(sizePolicy)
        self.txt_info.setTabChangesFocus(True)
        self.txt_info.setObjectName("txt_info")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.txt_info)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_2.setStyleSheet("border: 1px solid #8f8f91;\n"
"    border-radius: 6px;\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #f6f7fa, stop: 1 #dadbde);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_copybook = QtWidgets.QPushButton(self.frame_2)
        self.btn_copybook.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_copybook.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.btn_copybook.setFont(font)
        self.btn_copybook.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_copybook.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_copybook.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon/addressbook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_copybook.setIcon(icon1)
        self.btn_copybook.setIconSize(QtCore.QSize(32, 32))
        self.btn_copybook.setObjectName("btn_copybook")
        self.horizontalLayout.addWidget(self.btn_copybook)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_clear_file = QtWidgets.QPushButton(self.frame_2)
        self.btn_clear_file.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_clear_file.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.btn_clear_file.setFont(font)
        self.btn_clear_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear_file.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_clear_file.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/res/icon/decline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_clear_file.setIcon(icon2)
        self.btn_clear_file.setIconSize(QtCore.QSize(32, 32))
        self.btn_clear_file.setObjectName("btn_clear_file")
        self.horizontalLayout.addWidget(self.btn_clear_file)
        self.btn_file = QtWidgets.QPushButton(self.frame_2)
        self.btn_file.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_file.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.btn_file.setFont(font)
        self.btn_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_file.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_file.setText("")
        self.btn_file.setIcon(icon)
        self.btn_file.setIconSize(QtCore.QSize(32, 32))
        self.btn_file.setObjectName("btn_file")
        self.horizontalLayout.addWidget(self.btn_file)
        self.btn_ok = QtWidgets.QPushButton(self.frame_2)
        self.btn_ok.setMinimumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.btn_ok.setFont(font)
        self.btn_ok.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ok.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ok.setAutoFillBackground(False)
        self.btn_ok.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_ok.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/res/icon/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ok.setIcon(icon3)
        self.btn_ok.setIconSize(QtCore.QSize(32, 32))
        self.btn_ok.setAutoDefault(True)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_restore = QtWidgets.QPushButton(self.frame_2)
        self.btn_restore.setEnabled(False)
        self.btn_restore.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_restore.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.btn_restore.setFont(font)
        self.btn_restore.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_restore.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_restore.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/res/icon/transfer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_restore.setIcon(icon4)
        self.btn_restore.setIconSize(QtCore.QSize(32, 32))
        self.btn_restore.setObjectName("btn_restore")
        self.horizontalLayout.addWidget(self.btn_restore)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.frame_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.dta_inflow, self.cbo_document_name)
        Form.setTabOrder(self.cbo_document_name, self.txt_document_sign)
        Form.setTabOrder(self.txt_document_sign, self.dta_document_issue)
        Form.setTabOrder(self.dta_document_issue, self.txt_file)
        Form.setTabOrder(self.txt_file, self.txt_info)
        Form.setTabOrder(self.txt_info, self.btn_copybook)
        Form.setTabOrder(self.btn_copybook, self.btn_clear_file)
        Form.setTabOrder(self.btn_clear_file, self.btn_file)
        Form.setTabOrder(self.btn_file, self.btn_ok)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Dokument"))
        self.lbl_projectId.setText(_translate("Form", "Numer Inwestycji"))
        self.lbl_task_name.setText(_translate("Form", "Nazwa zadania"))
        self.lbl_inflow.setText(_translate("Form", "Data wpływu"))
        self.dta_inflow.setDisplayFormat(_translate("Form", "yyyy.MM.dd"))
        self.lbl_document_name.setText(_translate("Form", "Nazwa"))
        self.lbl_document_sign.setText(_translate("Form", "Znak"))
        self.lbl_document_issue.setText(_translate("Form", "Data wydania"))
        self.dta_document_issue.setDisplayFormat(_translate("Form", "yyyy.MM.dd"))
        self.lbl_info.setText(_translate("Form", "Uwagi"))
        self.lbl_file.setText(_translate("Form", "Plik"))
        self.btn_copybook.setToolTip(_translate("Form", "Notatnik"))
        self.btn_clear_file.setToolTip(_translate("Form", "Usuń nazwę pliku"))
        self.btn_file.setToolTip(_translate("Form", "Nazwa pliku"))
        self.btn_ok.setToolTip(_translate("Form", "Zapisz"))
        self.btn_restore.setToolTip(_translate("Form", "Przywróć dane"))
import res.main_form_rc
