# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'owner_inspector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.ApplicationModal)
        Form.resize(300, 680)
        Form.setMinimumSize(QtCore.QSize(300, 680))
        Form.setMaximumSize(QtCore.QSize(300, 680))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icon/avatar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.lstvw_owners = QtWidgets.QListView(Form)
        self.lstvw_owners.setGeometry(QtCore.QRect(10, 10, 281, 661))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lstvw_owners.setFont(font)
        self.lstvw_owners.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.lstvw_owners.setFrameShape(QtWidgets.QFrame.Box)
        self.lstvw_owners.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lstvw_owners.setAlternatingRowColors(True)
        self.lstvw_owners.setWordWrap(True)
        self.lstvw_owners.setItemAlignment(QtCore.Qt.AlignLeading)
        self.lstvw_owners.setObjectName("lstvw_owners")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Właściciele"))
import res.main_form_rc
