# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'segment_inspector.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SegmentInspector(object):
    def setupUi(self, SegmentInspector):
        SegmentInspector.setObjectName("SegmentInspector")
        SegmentInspector.setWindowModality(QtCore.Qt.ApplicationModal)
        SegmentInspector.resize(205, 550)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SegmentInspector.sizePolicy().hasHeightForWidth())
        SegmentInspector.setSizePolicy(sizePolicy)
        SegmentInspector.setMinimumSize(QtCore.QSize(205, 550))
        SegmentInspector.setMaximumSize(QtCore.QSize(205, 550))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        SegmentInspector.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icon/tasks.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SegmentInspector.setWindowIcon(icon)
        SegmentInspector.setWhatsThis("")
        self.verticalLayout = QtWidgets.QVBoxLayout(SegmentInspector)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lstvw_segments = QtWidgets.QListView(SegmentInspector)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.lstvw_segments.setFont(font)
        self.lstvw_segments.setFrameShape(QtWidgets.QFrame.Box)
        self.lstvw_segments.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.lstvw_segments.setAlternatingRowColors(True)
        self.lstvw_segments.setViewMode(QtWidgets.QListView.ListMode)
        self.lstvw_segments.setObjectName("lstvw_segments")
        self.verticalLayout.addWidget(self.lstvw_segments)

        self.retranslateUi(SegmentInspector)
        QtCore.QMetaObject.connectSlotsByName(SegmentInspector)

    def retranslateUi(self, SegmentInspector):
        _translate = QtCore.QCoreApplication.translate
        SegmentInspector.setWindowTitle(_translate("SegmentInspector", "Segment Inspektor"))
import res.main_form_rc
