# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'table_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 278)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/res/icon/logo_small.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(15, -1, 15, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_table = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_table.sizePolicy().hasHeightForWidth())
        self.lbl_table.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_table.setFont(font)
        self.lbl_table.setObjectName("lbl_table")
        self.verticalLayout_2.addWidget(self.lbl_table)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, 6, -1, 9)
        self.formLayout.setHorizontalSpacing(9)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.sbx_columns = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbx_columns.sizePolicy().hasHeightForWidth())
        self.sbx_columns.setSizePolicy(sizePolicy)
        self.sbx_columns.setMinimumSize(QtCore.QSize(100, 0))
        self.sbx_columns.setMinimum(2)
        self.sbx_columns.setMaximum(500)
        self.sbx_columns.setObjectName("sbx_columns")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.sbx_columns)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.sbx_rows = QtWidgets.QSpinBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbx_rows.sizePolicy().hasHeightForWidth())
        self.sbx_rows.setSizePolicy(sizePolicy)
        self.sbx_rows.setMinimumSize(QtCore.QSize(100, 0))
        self.sbx_rows.setMaximumSize(QtCore.QSize(100, 16777215))
        self.sbx_rows.setMinimum(1)
        self.sbx_rows.setMaximum(500000)
        self.sbx_rows.setObjectName("sbx_rows")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.sbx_rows)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_tcaption = QtWidgets.QLineEdit(Form)
        self.txt_tcaption.setObjectName("txt_tcaption")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_tcaption)
        self.verticalLayout_2.addLayout(self.formLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 6, -1, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbx_tfooter = QtWidgets.QCheckBox(Form)
        self.cbx_tfooter.setObjectName("cbx_tfooter")
        self.verticalLayout.addWidget(self.cbx_tfooter)
        self.cbx_theader = QtWidgets.QCheckBox(Form)
        self.cbx_theader.setObjectName("cbx_theader")
        self.verticalLayout.addWidget(self.cbx_theader)
        self.cbx_tborder = QtWidgets.QCheckBox(Form)
        self.cbx_tborder.setObjectName("cbx_tborder")
        self.verticalLayout.addWidget(self.cbx_tborder)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line = QtWidgets.QFrame(Form)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_ok = QtWidgets.QPushButton(Form)
        self.btn_ok.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_ok.setStyleSheet("QPushButton {\n"
"border: 1px solid #8f8f91;\n"
"border-radius: 6px;\n"
"background-color: qlineargradient(spread:pad, x1:0.529318, y1:1, x2:0.511909, y2:0.262, stop:0.295455 rgba(192, 192, 192, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0.507, y1:0.937, x2:0.489, y2:0.08, stop:0 rgba(207, 207, 207, 255), stop:1 rgba(255, 255, 255, 255))\n"
" }\n"
"QPushButton:pressed {\n"
" background-color: qlineargradient(spread:pad, x1:0.513, y1:0, x2:0.495, y2:0.886, stop:0.306818 rgba(208, 208, 208, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.btn_ok.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/res/icon/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_ok.setIcon(icon1)
        self.btn_ok.setIconSize(QtCore.QSize(32, 32))
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout.addWidget(self.btn_ok)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.sbx_columns, self.sbx_rows)
        Form.setTabOrder(self.sbx_rows, self.txt_tcaption)
        Form.setTabOrder(self.txt_tcaption, self.cbx_tfooter)
        Form.setTabOrder(self.cbx_tfooter, self.cbx_theader)
        Form.setTabOrder(self.cbx_theader, self.cbx_tborder)
        Form.setTabOrder(self.cbx_tborder, self.btn_ok)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Tabela"))
        self.lbl_table.setText(_translate("Form", "Właściwości tabeli:"))
        self.label_3.setText(_translate("Form", "Kolumn"))
        self.label_2.setText(_translate("Form", "Wierszy"))
        self.label.setText(_translate("Form", "Nagłówek"))
        self.cbx_tfooter.setText(_translate("Form", "Wiersz stopki"))
        self.cbx_theader.setText(_translate("Form", "Wiersz nagłówka"))
        self.cbx_tborder.setText(_translate("Form", "Niewidoczne krawędzie"))
import res.main_form_rc
